In [1]:
# Build a simple neural network

In [2]:
import numpy as np

In [40]:
class Network:
    def __init__(self, size):
        self.bias = [np.random.randn(size, 1) for i in size]
        self.weight = [np.random.randn(x, y) for x, y in zip(size[:-1], size[1:])]
        
    def forward(self, a):
        for w, b in zip(self.weight, self.bias):
            a = sigmoid(np.dot(self.weight, a))
        return a
    
    def 
    
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [12]:
x = np.random.randn(2, 1)
print(x)

[[-0.74511131]
 [ 1.03776134]]


In [7]:
# Assume that there is x_1 and x_2
# Initialize the weight

w_1 = np.random.randn(3, 2)
w_2 = np.random.randn(3, 1)
b_1 = np.zeros((3, 1))
b_2 = np.zeros((1, 1))
print(w_1)
print(b_1)
print(b_2)

[[ 1.1704761   0.29213245]
 [ 1.59965977 -0.64948241]
 [ 0.034346   -0.28938309]]
[[0.]
 [0.]
 [0.]]
[[0.]]


In [14]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [18]:
# This is for forward propagation
z_1 = np.dot(w_1, x) + b_1
a_1 = sigmoid(z)
z_2 = np.dot(w_2.T, a) + b_2
a_2 = sigmoid(z)

In [21]:
a_2.shape

3

In [42]:
layer_1 = Layer(3, sigmoid)

In [43]:
layer_1.forward(x)

In [45]:
layer_2 = Layer(1, sigmoid)

In [46]:
layer_2.forward(layer_1.hidden_nodes)

In [ ]:
layer2